import { CCIDynamicBotOptions } from './bot';

export const BTCUSDT: CCIDynamicBotOptions = {
    instrumentType: 'FUTURES',
    fee: 0.02,
    lotsMultiplier: 1,
    equityLevel: 1,
    broker: 'binance',
    ticker: 'BTCUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    orderCandlesLimit: 76,
    closeAtZero: false,
    stopTakeRatio: 1.47,
    atrPeriod: 30,
    atrMultiplier: 3.45,
    levelPeriod: 31,
    levelRedunant: 0.84,
    levelSampleCount: 2,
    levelSampleType: 2,
    levelMultiplier: 2.38,
    levelOffset: 0,
    cciPeriod: 35,
    zeroClose: true,
    sandbox: true,
    cciAtr: false,
    maxRetryOrders: 3,
    reduceWhen: 1.05,
    reduceSize: 0.22,
    manual: true,
    id: 4,
    signalFilter: false,
    takeProfit: 8.74,
    stopLoss: 9.1,
    trailing: 2,
};

export const SBER: CCIDynamicBotOptions = {
    instrumentType: 'SPOT',
    fee: 0.02,
    lotsMultiplier: 1,
    equityLevel: 1,
    broker: 'tinkoff',
    ticker: 'SBER',
    currency: 'RUB',
    interval: '15min',
    amount: 500,
    maxRetryOrders: 0,
    orderCandlesLimit: 100,
    closeAtZero: false,
    stopTakeRatio: 2,
    atrPeriod: 21,
    atrMultiplier: 5.48,
    levelPeriod: 30,
    levelRedunant: 0.27,
    levelSampleCount: 2,
    levelSampleType: 2,
    levelMultiplier: 1,
    levelOffset: 0,
    cciPeriod: 13,
    zeroClose: false,
    sandbox: true,
    cciAtr: false,
    id: 29,
};

export const BNBUSDT: CCIDynamicBotOptions = {
    ticker: 'BNBUSDT',
    currency: 'USDT',
    broker: 'binance',
    interval: '15min',
    amount: 10000,
    levelOffset: 0,
    stopTakeRatio: 1.26,
    atrPeriod: 14,
    atrMultiplier: 1.69,
    cciPeriod: 32,
    levelPeriod: 32,
    levelSampleType: 4,
    levelRedunant: 0.45,
    levelSampleCount: 3,
    levelMultiplier: 1.05,
    cciAtr: false,
    closeAtZero: true,
    orderCandlesLimit: 11,
    zeroClose: true,
    signalFilter: true,
    takeProfit: 2.87,
    stopLoss: 1.45,
    reduceWhen: 4.17,
    reduceSize: 0.87,
    trailing: 2,
    id: 29,
    sandbox: true,
};

export const ENSUSDT: CCIDynamicBotOptions = {
    ticker: 'ENSUSDT',
    currency: 'USDT',
    broker: 'binance',
    interval: '15min',
    amount: 1000,
    levelOffset: 0,
    stopTakeRatio: 3.27,
    atrPeriod: 29,
    atrMultiplier: 7.49,
    cciPeriod: 36,
    levelPeriod: 19,
    levelSampleType: 2,
    levelRedunant: 0.73,
    levelSampleCount: 2,
    levelMultiplier: 1.51,
    cciAtr: true,
    closeAtZero: false,
    orderCandlesLimit: 40,
    zeroClose: false,
    signalFilter: true,
    takeProfit: 2.13,
    stopLoss: 2.05,
    reduceWhen: 1.82,
    reduceSize: 0.22,
    trailing: 0,
    sandbox: true,
    id: 4,
    reinvest: true,
};
export const CRVUSDT: CCIDynamicBotOptions = {
    ticker: 'CRVUSDT',
    currency: 'USDT',
    broker: 'binance',
    interval: '15min',
    amount: 10000,
    levelOffset: 0,
    stopTakeRatio: 3.34,
    atrPeriod: 12,
    atrMultiplier: 3.76,
    cciPeriod: 12,
    levelPeriod: 18,
    levelSampleType: 4,
    levelRedunant: 0.89,
    levelSampleCount: 4,
    levelMultiplier: 1.51,
    cciAtr: true,
    closeAtZero: false,
    orderCandlesLimit: 83,
    zeroClose: false,
    signalFilter: true,
    takeProfit: 1.96,
    stopLoss: 9.22,
    reduceWhen: 4.83,
    reduceSize: 0.43,
    trailing: 0,
    sandbox: true,
    id: 29,
};
