import { CCIDynamic1BotOptions } from './bot';

export const SBER: CCIDynamic1BotOptions = {
    instrumentType: 'SPOT',
    fee: 0.02,
    lotsMultiplier: 1,
    equityLevel: 1,
    broker: 'tinkoff',
    ticker: 'SBER',
    currency: 'RUB',
    interval: '15min',
    amount: 1000,
    // maxRetryOrders: 0,
    orderCandlesLimit: 19,
    closeAtZero: false,
    stopTakeRatio: 3.28,
    atrPeriod: 37,
    atrMultiplier: 5.09,
    levelPeriod: 7,
    levelRedunant: 0.87,
    levelSampleCount: 1,
    levelSampleType: 4,
    levelMultiplier: 2.47,
    levelOffset: 0,
    cciPeriod: 8,
    zeroClose: false,
    sandbox: true,
    cciAtr: true,
    id: 4,
    signalFilter: false,
    takeProfit: 4.21,
    stopLoss: 2,
    // stopLoss: 7.08,
    // reduceWhen: 1.07,
    // reduceSize: 0.23,
    // trailing: 0,
};

export const ENSUSDT: CCIDynamic1BotOptions = {
    ticker: 'ENSUSDT',
    instrumentType: 'SPOT',
    currency: 'USDT',
    broker: 'binance',
    interval: '15min',
    amount: 10000,
    levelOffset: 0,
    stopTakeRatio: 1.43,
    equityLevel: 0.01,
    atrPeriod: 23,
    atrMultiplier: 9.85,
    cciPeriod: 14,
    levelPeriod: 34,
    levelSampleType: 1,
    levelRedunant: 0.39,
    levelSampleCount: 2,
    levelMultiplier: 1.65,
    cciAtr: true,
    closeAtZero: false,
    orderCandlesLimit: 48,
    zeroClose: true,
    signalFilter: false,
    takeProfit: 0.1,
    stopLoss: 0.1,
    // manual: true,
    // stopLoss: 2.14,
    // reduceWhen: 2.55,
    // reduceSize: 0.22,
    // trailing: 1,
    sandbox: true,
    id: 4,
    reinvest: true,
};
